### PR TITLE
Update to 5.5.0 [DEX-192][REL-289]

### PR DESCRIPTION
**Pull request by frant-hartm**
Updates dependency on Hazeclast to 5.5.0-SNAPSHOT, adds private repository with the snapshot, because they were removed from central snapshot repository.

### CODE REVIEW

**Comment by jerrinot** [comment]
@frant-hartm does it mean `hazelcast-jdbc` is no longer publicly buildable without patching build scripts?

**Comment by frant-hartm** [comment]
@jerrinot 
For the period between when this PR gets merged and `5.5.0` is released you would need to build the `5.5.0-SNAPSHOT` yourself from the sources in https://github.com/hazelcast/hazelcast

**Comment by nishaatr** [comment]
I believe @kwart is off on vacation
note: we also have https://github.com/hazelcast/hazelcast-jdbc/pull/370

**Comment by JackPGreen** [comment]
The GitHub diff looks broken - it's showing changes that are already present on `main`.
Updating the target branch to force re-evaluation.

**Comment by JackPGreen** [comment]
This PR appears to duplicate https://github.com/hazelcast/hazelcast-jdbc/pull/362

**Pull request closed without merging**
